### ISSUE TITLE
MapImage: Cannot find module 'request'

### ISSUE THREAD

**Issue by ScottBrenner** [heremaps/here-aws-sar#2]
I've just deployed MapImage from the AWS Serverless Application Repository (https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:242721718429:applications~MapImage) but am seeing the below error when visiting `https://<apigw>.execute-api.<region>.amazonaws.com/Stage/mapimage?t=1&lat=63.529722&lon=-19.513889`, any tips?

`{"errorMessage":"Cannot find module 'request'","errorType":"Error","stackTrace":["Object.<anonymous> (/var/task/mapimage.js:25:17)","Module._compile (module.js:570:32)","Object.Module._extensions..js (module.js:579:10)","Module.load (module.js:487:32)","tryModuleLoad (module.js:446:12)","Function.Module._load (module.js:438:3)"]}`

**Comment by antondelsink** [comment]
The error message reminds me of what happens when the "npm update" step is skipped.

I can confirm packaging anew from SAM, creating a new AWS SAR entry, and deploying from that new AWS SAR entry works as expected; @palermo4 please redeploy this one...
 
CC @ScottBrenner

**Comment by palermo4** [comment]
Dependencies issue resolved.
